<!DOCTYPE html>
<html>
    <head>
        <title>HPD III</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="../public/css/style.css">
        <link rel="stylesheet" href="../public/css/bootstrap.min.css">
        <link rel="stylesheet" href="../public/css/custom.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script type='text/javascript' scr="../public/js/bootstrap.min.js"></script>
        <script type='text/javascript' src='../public/js/javascript.js'></script>
        <style>
            /*** MOVE THIS TO custom.css. Due to a bug on my machine, it won't render any new material */
            .p-2:hover {
                cursor: pointer;
                color: black;
                transition: 0.18s;
            }

            .p-2 {
                color: #333;
            }
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <div class="main-wrapper-first">
                <div class="jumbotron">
                    <div class="container">
                        <div class="d-flex flex-row">
                            <h1 class="display-3">About</h1>
                        </div>
                        <div class="d-flex flex-row">
                            <h3 id="scnd_t" class="p-2" onclick="navigate('home')"><i class="fa fa-arrow-circle-o-right ml-2"></i> Home</h3>
                            <h3 id="scnd_t" class="p-2" onclick="navigate('about')"><i class="fa fa-arrow-circle-o-right ml-2"></i> About</h3>
                            <h3 id="scnd_t" class="p-2" onclick="navigate('contact')"><i class="fa fa-arrow-circle-o-right ml-2"></i> Contact Us</h3>
                        </div>
                    </div>
                </div>
                <h2>Lorem</h2>
                <p>Lorem ipsum. Ip lorem lor ip ip lorem. Lor ipsum sum ip lor sum? Lorem ipsum! Lorem lor ip lor sum lor ipsum</p>
            </div>
        </div>
    </body>

</html>
