<!DOCTYPE html>
<html>
    <head>
        <title>HPD III</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="../public/css/style.css">
        <link rel="stylesheet" href="../public/css/bootstrap.min.css">
        <link rel="stylesheet" href="../public/css/custom.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
        <script type='text/javascript' scr="../public/js/bootstrap.min.js"></script>
        <script type='text/javascript' src='../public/js/javascript.js'></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
        <style>
            /*** MOVE THIS TO custom.css. Due to a bug on my machine, it won't render any new material */
            .p-2:hover {
                cursor: pointer;
                color: black;
                transition: 0.18s;
            }

            .p-2 {
                color: #333;
            }
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <div class="main-wrapper-first">
                <div class="jumbotron">
                    <div class="container">
                        <div class="d-flex flex-row">
                            <h1 class="display-3">HPD</h1>
                        </div>
                        <blockquote>
                            <p class="lead">This is the client page. When "More" button is clicked a modal is triggered displaying addition info. The load more users at the bottom of the page will load the next 6 owners from the database</p>
                        </blockquote>
                        <div class="d-flex flex-row">
                            <h3 id="scnd_t" class="p-2" onclick="navigate('home')"><i class="fa fa-arrow-circle-o-right ml-2"></i> Home</h3>
                            <h3 id="scnd_t" class="p-2" onclick="navigate('about')"><i class="fa fa-arrow-circle-o-right ml-2"></i> About</h3>
                            <h3 id="scnd_t" class="p-2" onclick="navigate('contact')"><i class="fa fa-arrow-circle-o-right ml-2"></i> Contact Us</h3>
                        </div>
                    </div>

                </div>
                <div class="btnfiltergroup">
                    <button class="btn btn-lg option" onclick="showFilter()">Filter</button>
                </div>
                <div id="filterForm" style="display:none;">
                    <div class="jumbotron-fluid">
                        <h1><span class="label label-primary"><i class='fas fa-filter'style="padding-right:1em;"></i>Search</span></h1>
                        <div class="form-group">
                            <div class="input-group pad">
                                <span class="input-group-addon">First Name</span>
                                <input class="form-control" type="text" size="12" name=fnamefilter value="">
                            </div>
                            <div class="input-group pad">
                                <span class="input-group-addon">Last Name</span>
                                <input class="form-control" type="text" size="12" name=lnamefilter value="">
                            </div>
                            <div class="input-group pad">
                                <span class="input-group-addon">Street1</span>
                                <input class="form-control" type="text" size="12" name=street1filter value="">
                            </div>
                            <div class="input-group pad">
                                <span class="input-group-addon">Street2</span>
                                <input class="form-control" type="text" size="12" name=street2filter value="">
                            </div>
                            <div class="input-group pad">
                                <span class="input-group-addon">City</span>
                                <input class="form-control" type="text" size="12" name=cityfilter value="">
                            </div>
                            <div class="input-group pad">
                                <span class="input-group-addon">State</span>
                                <input class="form-control" type="text" size="12" name=statefilter value="">
                            </div>
                            <div class="input-group pad">
                                <span class="input-group-addon">Zip</span>
                                <input class="form-control" type="text" size="12" name=zipfilter value="">
                            </div>


                            <div class="input-group pad">
                                <span class="input-group-addon">Policy</span>
                                <input class="form-control" type="text" size="12" name=policyfilter value="">
                            </div>
                            <div class="input-group pad">
                                <span class="input-group-addon">Expiration</span>
                                <input class="form-control" type="text" size="12" name=expirationfilter value="">
                            </div>
                            <button onClick="filter()">Filter</button></th>
                        </div>
                    </div>
                </div>
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


                <table class="table table-hover">
                    <thead>
                        <tr id="filterRow">
                            <th class="theader"><span onclick="showFilter()"><i class="fas fa-filter"></i></span>
                            </th>
                            <th class="theader"><span onclick="sortBy('fname')">First <span class = "filterIcon">▲</span><br></span>
                            </th>
                            <th class="theader"> <span onclick="sortBy('lname')">Last <span class = "filterIcon">▲</span><br></span>
                            </th>
                            <th class="theader"> <span onclick="sortBy('street1')">Address 1 <span class = "filterIcon"><span class = "filterIcon">▲</span></span><br></span>
                            </th>
                            <th class="theader"><span onclick="sortBy('street2')">Address 2 <span class = "filterIcon">▲</span><br></span>
                            </th>
                            <th class="theader"> <span onclick="sortBy('city')">City <span class = "filterIcon">▲</span><br></span>
                            </th>
                            <th class="theader"> <span onclick="sortBy('state')">State <span class = "filterIcon">▲</span><br></span>
                            </th>
                            <th class="theader"><span onclick="sortBy('zip')">Zip <span class = "filterIcon">▲</span><br></span>
                            </th>
                            <th class="theader"> <span onclick="sortBy('policy')">Policy <span class = "filterIcon">▲</span><br></span>
                            </th>
                            <th class="theader"> <span onclick="sortBy('expiration')">Expiration <span class = "filterIcon">▲</span><br></span>
                            </th>
                        </tr>
                        <tbody id="itemsTableBody">
                        </tbody>
                </table>
                <div class='modal fade' id='updateModal' tabindex='-1' role='dialog' aria-labelledby='exampleModalLabel' aria-hidden='true'>
                    <div class='modal-dialog modal-lg modal-lg modal-dialog-centered' role='document'>
                        <div class='modal-content'>
                            <div class='modal-header'>
                                <h5 class='modal-title' id='ModalLabel'>Update Owner</h5>
                                <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                    </button>
                            </div>
                            <div class='modal-body' id="modalBody">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>First</th>
                                            <th>Last</th>
                                            <th>Address 1</th>
                                            <th>Address 2</th>
                                            <th>City</th>
                                            <th>State</th>
                                            <th>Zip</th>
                                            <th>Policy</th>
                                            <th>Expiration</th>
                                        </tr>
                                    </thead>
                                    <tbody id="updateModalTableBody">
                                        <!-- THIS IS WHERE THE MAGIC HAPPENS -->
                                    </tbody>
                                </table>
                                <div class='modal-footer'>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class='modal fade' id='myModal' tabindex='-1' role='dialog' aria-labelledby='exampleModalLabel' aria-hidden='true'>
                    <div class='modal-dialog modal-lg modal-lg modal-dialog-centered' role='document'>
                        <div class='modal-content'>
                            <div class='modal-header'>
                                <h5 class='modal-title' id='ModalLabel'>Items</h5>
                                <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                    </button>
                            </div>
                            <div class='modal-body' id="modalBody">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>Name</th>
                                            <th>Photo</th>
                                            <th>Description</th>
                                            <th>Valuation</th>
                                            <th>Method</th>
                                            <th>Verified</th>
                                        </tr>
                                    </thead>
                                    <tbody id="modalTableBody">
                                    </tbody>

                                </table>
                                <div class='modal-footer'>
                                    <button type='button' class='btn btn-secondary' data-dismiss='modal'>Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class='modal fade' id='updateItemModal' tabindex='-1' role='dialog' aria-labelledby='exampleModalLabel' aria-hidden='true'>
                    <div class='modal-dialog modal-lg modal-lg modal-dialog-centered' role='document'>
                        <div class='modal-content'>
                            <div class='modal-header'>
                                <h5 class='modal-title' id='ModalLabel'>Items</h5>
                                <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                        </button>
                            </div>
                            <div class='modal-body' id="modalBody">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Photo</th>
                                            <th>Description</th>
                                            <th>Valuation</th>
                                            <th>Method</th>
                                            <th>Verified</th>
                                        </tr>
                                    </thead>
                                    <tbody id="updateItemModalTableBody">
                                        <!-- THIS IS WHERE THE MAGIC HAPPENS -->
                                    </tbody>

                                </table>
                                <div class='modal-footer'>
                                    <button type='button' class='btn btn-secondary' data-dismiss='modal'>Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <ul class="pagination">
                    <li><span onClick="lastP()">Prev</span>&nbsp&nbsp </li>
                    <li><span onClick="nextP()">Next</span></li>
                </ul>
            </div>

        </div>
        <script>
        function showFilter() {
            $("#filterForm").toggle();
        }

        </script>
    </body>

</html>
