<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="../public/css/bootstrap.min.css">
        <link rel="stylesheet" href="../public/css/custom.css">
        <script type="text/javascript" src="../public/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script type="text/javascript" src="../public/js/controller.js"></script>
        <style>
            body {
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: black;
                font-size: 18px;
            }

            h1 {
                color: black;
                font-weight: 200;
            }
        </style>
    </head>
    <body>
        <div class='login-wrapper'>
          <div class='login-panel'>
          <h1>LOGIN</h1>
          <form id="LoginForm">
            <div class="form-group">
              <label for="exampleInputEmail1">First Name</label>
              <input type="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="First Name">
              <small id="emailHelp" class="form-text text-muted">We'll never share your info with anyone else.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Policy Number</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Policy Number">
            </div>
            <div class="form-group form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Stay Logged In</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
          </div>
        </div>
    </body>
</html>
